"""add heartbeat + device live fields

Revision ID: 782190dd2f22
Revises: 5ccf8fd2b265
Create Date: 2025-10-13 09:24:22.386460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782190dd2f22'
down_revision: Union[str, Sequence[str], None] = '5ccf8fd2b265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('total_bytes', sa.BigInteger(), nullable=True))
    op.add_column('devices', sa.Column('used_bytes', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'used_bytes')
    op.drop_column('devices', 'total_bytes')
    op.drop_column('devices', 'last_seen')
    # ### end Alembic commands ###
